apiVersion: apps/v1
kind: Deployment
metadata:
  name: Spring-Boot-App
  labels:
    app: Spring-Boot-App
    owner: Valerii_Vasianovych
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Spring-Boot-App
  template:
    metadata:
      labels:
        app: Spring-Boot-App
    spec:
      containers:
        - name: Spring-Boot-App
          image: 312211201134.dkr.ecr.us-east-1.amazonaws.com/spring:1.1
          ports:
            - containerPort: 8080

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: spring-boot-app-as
  labels:
    app: Spring-Boot-App
    owner: Valerii_Vasianovych
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: Spring-Boot-App
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80